name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22, 24]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Generating ci badge JSONs
      if: ${{ matrix.node-version == 20 }}
      uses: gaelgirodon/ci-badges-action@v1
      with:
        gist-id: 334525743d4f008bb0028808bfc44798
        token: ${{ secrets.GIST_TOKEN }}
        ref: true
    - uses: actions/upload-artifact@v4
      with:
        name: coverage-artifacts-${{ matrix.node-version }}
        path: coverage # or path/to/artifact

    - name: Jest Coverage Comment
      uses: MishaKav/jest-coverage-comment@main
