name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Update Coverage Badge
      if: ${{ matrix.node-version == 20.x }}
      uses: we-cli/coverage-badge-action@main
    - uses: actions/upload-artifact@v4
      with:
        name: coverage-artifacts-${{ matrix.node-version }}
        path: coverage # or path/to/artifact
